name: Feature request
description: Suggest an idea for this project
title: '[FEAT] '
labels: ['feature']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to have.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Add any other context e.g screenshots or a sketch about the feature request here.